#!/usr/bin/env python3
"""Run with ~/tunepile/.venv/bin/python. Real MIDI timing + translated melodies."""
from pathlib import Path
from collections import defaultdict
import re
from music21 import midi

root = Path(__file__).resolve().parents[1]
pile = Path('/home/erik/tunepile')
lines = ['-- 70: OPEN WINDOWS. LPViz / Bjork / Radiohead / three human MIDI grooves.',
         '-- 99 BPM, 48-bar drum journey against 7-bar vocal and 4-bar keyboard phrases.',
         '-- Load sc/samples70.scd and sc/open70.scd first. No ricochet FX.',
         '-- Generated by tools/build_corpus70.py; sources in sc/corpus70.md.', '']

sources = ['10_soul-groove10_102_beat_4-4.mid', '2_funk-groove2_105_beat_4-4.mid', '6_hiphop-groove6_87_beat_4-4.mid']
counts = {}
for clip, filename in enumerate(sources):
    mf = midi.MidiFile()
    mf.open(str(pile / 'midi/groove/groove/drummer1/eval_session' / filename))
    mf.read(); mf.close()
    length = 32 * mf.ticksPerQuarterNote
    voices = [defaultdict(list) for _ in range(3)]
    for track in mf.tracks:
        tick = 0
        for event in track.events:
            if event.isDeltaTime():
                tick += event.time
            elif event.type == midi.ChannelVoiceMessages.NOTE_ON and event.velocity > 0 and 0 <= tick < length:
                note, vel = event.pitch, event.velocity
                if note in (35, 36):
                    voice, sound, ceiling = 0, ['p70kick', 'bd:2', 'h2ogmbd:4'][clip], .67
                elif note in (37, 38, 40):
                    voice, sound, ceiling = 1, ('p70snare' if vel > 90 else 'p70soft'), .57
                elif note in (22, 26, 42, 44, 46):
                    voice, sound, ceiling = 2, ('808oh' if note in (26, 46) else 'p70hat'), .35
                else:
                    continue
                gain = ceiling * (vel / 127) ** .5
                voices[voice][tick].append(f's "{sound}" # gain {gain:.4f}')
    counts[filename] = [sum(map(len, v.values())) for v in voices]
    for i, notes in enumerate(voices):
        times = sorted(notes)
        parts = [(times[0], 'silence')] if times and times[0] else []
        for j, tick in enumerate(times):
            duration = (times[j+1] if j+1 < len(times) else length) - tick
            pattern = notes[tick][0] if len(notes[tick]) == 1 else 'stack [' + ', '.join(notes[tick]) + ']'
            parts.append((duration, '(' + pattern + ')'))
        body = ', '.join(f'({duration}, {pattern})' for duration, pattern in parts)
        lines += [f'let human70_{clip}_{i} = slow 8 $ timeCat [{body}]', '']

def translated(filename, stream, start, end):
    text = (pile / 'tabs-tidal' / filename).read_text()
    cells = re.search(r'^d' + str(stream) + r' \$ n "([^"]+)"', text, re.M)[1].split()
    return cells[start:end]

pcs = {'c': 0, 'd': 2, 'e': 4, 'f': 5, 'g': 7, 'a': 9, 'b': 11}
names = ['c', 'cs', 'd', 'ds', 'e', 'f', 'fs', 'g', 'gs', 'a', 'as', 'b']
def change_token(token, semitones=0, sample=False, minor=False):
    def change(match):
        letter, sharp, octave = match.groups()
        pitch = pcs[letter] + bool(sharp) + int(octave) * 12
        if minor and pitch % 12 in (4, 9):
            pitch -= 1
        pitch += semitones
        return str(pitch - 62) if sample else names[pitch % 12] + str(pitch // 12)
    return re.sub(r'([a-g])(s?)(\d+)', change, token)

vocal = translated('Bj_rk_-_All_Is_Full_Of_Love.gp4-97acf1f1.tidal', 4, 144, 256)
# Restore singing note lengths cautiously; leave gaps after at most seven held cells.
held = 0
for i, token in enumerate(vocal):
    if token != '~':
        vocal[i] = change_token(token, -5); held = 7
    elif held:
        vocal[i] = '_'; held -= 1
keyboard = translated('Radiohead_-_Everything_in_its_Right_Place.gp3-f0bed302.tidal', 1, 0, 64)
keyboard = [change_token(t, 12, sample=True, minor=True) for t in keyboard]
lines += [f'let love70 = slow 7 $ n "{" ".join(vocal)}"', '',
          f'let place70 = slow 4 $ up "{" ".join(keyboard)}"', '',
          'setcps (99/240)', '']

loop_a = 'loopAt 1 $ s "p70drumA" # gain 0.62'
loop_b = 'every 4 (chop 16) $ loopAt 2 $ s "p70drumB" # gain 0.61'
loop_c = 'struct "<t(11,16) t(9,16) t(13,16)>" $ chop 16 $ loopAt 2 $ s "p70drumB" # gain 0.58'
for voice in range(3):
    sections = [loop_a if voice == 0 else 'silence', f'human70_0_{voice}',
                loop_b if voice == 0 else 'silence', f'human70_1_{voice}',
                loop_c if voice == 0 else 'silence', f'human70_2_{voice}']
    body = ', '.join('(8, fast 8 $ ' + pattern + ')' for pattern in sections)
    lines += [f'd{voice+1} $ (slow 48 $ timeCat [{body}]) # lpf 18000 # hpf 30 # ddSend 0 # delaySend 0 # delayfeedback 0 # verbSend 0 # room 0', '']
lines += [
    'd4 $ stack [slow (5/4) $ s "p70body(3,8)" # speed "<0.8 1.1 1.4>" # gain 0.3 # pan 0.3, slow (7/4) $ n "0 3 7 12" # s "coffee(5,12)" # gain 0.29 # pan 0.7] # hpf 350 # lpf 12000 # ddSend 0 # delaySend 0 # delayfeedback 0', '',
    'd5 $ n "<[c3 ~ g3 ~] [c3 ~ ~ as2] [gs2 ~ ds3 ~] [gs2 ~ as2 ~] [f3 ~ c4 ~] [f3 ~ ~ gs2] [as2 ~ f3 ~] [g2 ~ ~ b2]>" # s "dubsub" # gain 0.57 # legato 0.4 # lpf 1100 # ddSend 0 # delaySend 0 # delayfeedback 0', '',
    'd6 $ (every 8 (chop 8) $ slow 8 $ timeCat [(4, fast 4 $ loopAt 2 $ s "p70synthA"), (4, fast 4 $ loopAt 2 $ s "p70synthB")]) # gain 0.64 # hpf 180 # lpf 16000 # cut 6 # ddSend 0.1 # delaySend 1 # delayfeedback 0.23 # ddWow 0 # ddCross 1 # verbSend 0.1', '',
    'd7 $ love70 # s "supersaw" # gain 0.7 # legato 0.88 # lpf 7800 # hpf 180 # pan (slow 11 $ range 0.35 0.65 sine) # ddSend 0.14 # delaySend 1 # lock 1 # delaytime (3/16) # delayfeedback 0.25 # ddWow 0 # ddCross 1 # verbSend 0.16 # verbT60 3.5', '',
    'd8 $ place70 # s "p70rhodes" # gain 0.56 # legato 0.75 # hpf 220 # lpf 11000 # pan 0.62 # ddSend 0.12 # delaySend 1 # lock 1 # delaytime (5/16) # delayfeedback 0.22 # ddWow 0 # ddCross 1 # verbSend 0.12', '',
    'd9 $ slow (7/4) $ struct "t f t f f t f f" $ chop 8 $ loopAt 1 $ s "p70vox" # gain 0.34 # cut 9 # hpf 400 # lpf 10000 # pan (slow 3 $ range 0.2 0.8 sine) # ddSend 0 # delaySend 0 # delayfeedback 0 # verbSend 0.12', '',
    'd10 $ slow (5/4) $ struct "t(5,8)" $ chop 8 $ loopAt 1 $ s "p70perc" # gain 0.32 # cut 10 # hpf 500 # lpf 16000 # pan 0.3 # ddSend 0 # delaySend 0 # delayfeedback 0', '',
    'd11 $ slow (3/2) $ s "icshaker(7,12)" # n "<0 1 4 2>" # speed "<1 0.82 1.17>" # gain 0.26 # hpf 1500 # lpf 16000 # pan 0.75 # ddSend 0 # delaySend 0 # delayfeedback 0', '',
    'd12 $ silence', '',
]
(root / '70.tidal').write_text('\n'.join(lines))
print('Built 70.tidal. MIDI events by kick/snare/hat:', counts)
