#!/usr/bin/env python3
"""Derive a clean 69.tidal without changing the approved wild suite."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
lines = []
for line in (root / '68.tidal').read_text().splitlines():
    if line.startswith('-- 68:'):
        line = '-- 69: GLASS / PRISM / CLEAR. Ricochet-free variant of 68; same form.'
    elif line.startswith('-- Generated by'):
        line = '-- Generated by tools/build_clean_suite.py; mixer: sc/melodic-clean.scd.'
    m = re.fullmatch(r'let (glass|prism|arcade)(\d{2}) = (.*)', line)
    if m:
        scene, index, pattern = m[1], int(m[2]), m[3]
        if index == 11 or (scene == 'glass' and index == 4) or (scene == 'arcade' and index == 9):
            pattern = 'silence'
        else:
            pattern = re.sub(r'every \d+ \(stut \d+ [\d.]+ \(1/\d+\)\) \$ ', '', pattern)
            pattern = pattern.replace('s "superchip"', 's "superpwm"')
        line = f'let {scene}{index:02d} = {pattern}'
    if re.match(r'd\d+ \$ ', line):
        index = int(re.match(r'd(\d+)', line)[1])
        line = line.replace('(s "clak ~ ~ ~" # gain 0.34 # hpf 1400 # ddSend 0.45 # lock 1 # delaytime (5/16) # delayfeedback 0.56)', 'silence')
        # Outer controls override even bridge events. Local feedback already
        # circulating on silent channels must also be cleared live on recall.
        body = line.split(' $ ', 1)[1]
        controls = ' # ddSend 0 # delaySend 0 # delayfeedback 0 # verbSend 0 # room 0' if index <= 5 or index == 11 else ' # ddSend 0.12 # delayfeedback 0.25 # ddWow 0 # ddCross 1 # ddDrive 0.08 # ddLp 2400'
        line = f'd{index} $ ({body}){controls}'
    lines.append(line)
(root / '69.tidal').write_text('\n'.join(lines) + '\n')
print('Built 69.tidal; removed clak/FM bursts, stutters and percussion echoes.')
