#!/usr/bin/env python3
"""Build standalone 68.tidal from the three independently playable scenes."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
scenes = {}
for number, name in [(65, 'glass'), (66, 'prism'), (67, 'arcade')]:
    patterns = {}
    for line in (root / f'{number}.tidal').read_text().splitlines():
        match = re.fullmatch(r'd(\d+) \$ (.*)', line)
        if match:
            patterns[int(match[1])] = match[2]
    assert set(patterns) == set(range(1, 13)), number
    scenes[name] = patterns

gains = {
    'glass': {6: .59, 7: .70, 8: .49, 9: .34, 10: .32, 11: 0, 12: 0},
    'prism': {6: .57, 7: .51, 8: .48, 9: .38, 10: .29, 11: .27, 12: 0},
    'arcade': {6: .47, 7: .43, 8: .52, 9: .36, 10: .30, 11: .27, 12: .33},
}

def bridge(a, b, i):
    if i == 1:
        return '(slow 8 $ timeCat [(4, silence), (4, fast 4 $ s "bd*2" # gain 0.65)])'
    if i == 2:
        return '(s "~ ~ sn ~" # gain 0.4 # hpf 600 # ddSend 0.4 # lock 1 # delaytime (3/16) # delayfeedback 0.54)'
    if i == 3:
        return '(s "hh(5,16)" # gain 0.28 # hpf 2400 # pan "0.25 0.75")'
    if i == 4:
        return '(s "clak ~ ~ ~" # gain 0.34 # hpf 1400 # ddSend 0.45 # lock 1 # delaytime (5/16) # delayfeedback 0.56)'
    if i == 5:
        return 'silence'
    return (f'(stack [{a}{i:02d} # gain (slow 8 $ range {gains[a][i]} 0 saw) # lpf 2200, '
            f'{b}{i:02d} # gain (slow 8 $ range 0 {gains[b][i]} saw) # lpf 3600])')

lines = [
    '-- 68: GLASS / PRISM / IMPOSSIBLE. Autonomous 128-bar melodic mashup suite.',
    '-- Generated by tools/build_scene_suite.py from 65.tidal, 66.tidal, 67.tidal.',
    '-- 0-31 glass; 32-39 crossfade; 40-71 prism; 72-79 crossfade;',
    '-- 80-111 arcade climax; 112-127 piano landing; repeats. 102 BPM.',
    '-- No custom scheduling helper; each section uses built-in slow/timeCat/fast.',
    '-- Definitions first, then clock and streams. No dependency on prior scenes.',
    '',
]
for name, patterns in scenes.items():
    for i, pattern in sorted(patterns.items()):
        lines += [f'let {name}{i:02d} = {pattern}', '']
lines += ['setcps (102/240)', '', 'resetCycles', '']
for i in range(1, 13):
    landing = f'glass{i:02d}'
    if i in (1, 2):
        landing = f'(slow 16 $ timeCat [(8, silence), (8, fast 8 glass{i:02d})])'
    elif i == 5:
        landing = '(slow 16 $ timeCat [(4, silence), (12, fast 12 glass05)])'
    elif i in (4, 11, 12):
        landing = 'silence'
    sections = [(32, f'glass{i:02d}'), (8, bridge('glass', 'prism', i)),
                (32, f'prism{i:02d}'), (8, bridge('prism', 'arcade', i)),
                (32, f'arcade{i:02d}'), (16, landing)]
    body = ', '.join(f'({bars}, fast {bars} $ {pattern})' for bars, pattern in sections)
    lines += [f'd{i} $ slow 128 $ timeCat [{body}]', '']
(root / '68.tidal').write_text('\n'.join(lines))
print('Built 68.tidal: 36 voice definitions, 12 streams, 128-bar form.')
