#!/usr/bin/env python3
"""Generate both sides of the Tidal <-> SuperDirt parameter contract.

A custom SuperDirt parameter has to exist in two places: declared in Tidal (or
evals fail with "Variable not in scope: ddSend") and listed in the effect's
GlobalDirtEffect in SuperCollider (or it is silently ignored). Remembering both
by hand is how the DSP layer spent an evening apparently not working.

So: `sc/params.tsv` is the single source of truth, and this script writes:

  1. the parameter block inside `BootTidal.hs` (between marker comments)
  2. `sc/params_gen.scd`, which defines ~dirtParamGroups for init.scd to consume

Usage:
  tools/sc_params.py            # generate both
  tools/sc_params.py --check    # fail if either output is stale (CI/hook use)
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
PARAMS = REPO / "sc/params.tsv"
BOOT = REPO / "BootTidal.hs"
GEN_SCD = REPO / "sc/params_gen.scd"

BEGIN = "-- BEGIN GENERATED PARAMS (tools/sc_params.py from sc/params.tsv)"
END = "-- END GENERATED PARAMS"

TIDAL_FN = {"f": "pF", "i": "pI", "s": "pS"}


def parse(path: pathlib.Path):
    """-> [(group, [(name, type)])] preserving file order."""
    groups: list[tuple[str, list[tuple[str, str]]]] = []
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        group, names = parts[0], parts[1:]
        if not names:
            print(f"params.tsv:{lineno}: '{group}' has no parameters", file=sys.stderr)
            return []
        parsed = []
        for n in names:
            if ":" in n:
                name, typ = n.split(":", 1)
            else:
                name, typ = n, "f"
            if typ not in TIDAL_FN:
                print(f"params.tsv:{lineno}: unknown type '{typ}' for {name}",
                      file=sys.stderr)
                return []
            parsed.append((name, typ))
        groups.append((group, parsed))
    return groups


def tidal_block(groups) -> str:
    lines = [BEGIN,
             "-- One binding per line: a multi-line `let` block is silently dropped",
             "-- when the file is loaded from a ghci script (-ghci-script)."]
    for group, params in groups:
        lines.append("")
        lines.append(f"-- {group}")
        for name, typ in params:
            lines.append(f'let {name} = {TIDAL_FN[typ]} "{name}"')
    lines.append("")
    lines.append(END)
    return "\n".join(lines)


def scd_block(groups) -> str:
    out = ["/* params_gen.scd — GENERATED by tools/sc_params.py from sc/params.tsv.",
           "   Do not edit by hand; edit the manifest and re-run the generator.",
           "   init.scd reads ~dirtParamGroups to build each GlobalDirtEffect's",
           "   parameter list, so a param cannot be added to one side only. */",
           "(",
           "~dirtParamGroups = ["]
    for group, params in groups:
        # COMMAS are required: in [\a \b] SuperCollider parses \b as a binary
        # operator ("unexpected SYMBOL, expecting ']'")
        syms = ", ".join(f"\\{n}" for n, _ in params)
        out.append(f"\t['{group}', [{syms}]],")
    out += ["];",
            '"params_gen: % group(s) loaded".format(~dirtParamGroups.size).postln;',
            ")"]
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if generated files are out of date")
    a = ap.parse_args()

    groups = parse(PARAMS)
    if not groups:
        raise SystemExit("sc/params.tsv could not be parsed")
    text_block = tidal_block(groups)

    boot_src = BOOT.read_text()
    if BEGIN in boot_src:
        boot_new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END),
                          lambda m: text_block, boot_src, flags=re.S)
    else:
        # place the block directly after the Boot import: chunks evaluated while
        # the script is still loading then find the params already defined
        anchor = "import Sound.Tidal.Boot"
        boot_new = (boot_src.replace(anchor, anchor + "\n\n" + text_block, 1)
                    if anchor in boot_src else boot_src.rstrip() + "\n\n" + text_block + "\n")

    scd_new = scd_block(groups)

    if a.check:
        stale = []
        if boot_new != boot_src:
            stale.append(str(BOOT.relative_to(REPO)))
        if not GEN_SCD.exists() or GEN_SCD.read_text() != scd_new:
            stale.append(str(GEN_SCD.relative_to(REPO)))
        if stale:
            print("stale generated files: " + ", ".join(stale), file=sys.stderr)
            raise SystemExit(1)
        print("generated files are up to date")
        raise SystemExit(0)

    BOOT.write_text(boot_new)
    GEN_SCD.write_text(scd_new)
    n = sum(len(p) for _, p in groups)
    print(f"{n} parameter(s) in {len(groups)} group(s) -> {BOOT.name}, {GEN_SCD.name}")
