#!/usr/bin/env python3
"""Build a searchable catalogue of the UGens installed on this machine.

SuperCollider ships its documentation as `.schelp` files, and this machine has
~1200 of them (core + SC3plugins: DEINDUGens, ATK, MCLD, Bhob, Josh, Stk, …).
Each records a title, a summary, categories and — crucially for us — the
**argument lists**, which is exactly what is needed to use a UGen without
guessing. This turns them into two files:

    sc/ugen-catalog.md     human/agent readable, grouped by category
    sc/ugen-catalog.json   machine readable (name, summary, args, source)

Usage:
  tools/ugen_catalog.py                # rebuild both files
  tools/ugen_catalog.py --find reverb  # search names/summaries/args
  tools/ugen_catalog.py --find 'granular' --args
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

HELP_DIRS = [
    pathlib.Path("/usr/share/SuperCollider/HelpSource/Classes"),
    pathlib.Path("/usr/share/SuperCollider/Extensions/SC3plugins"),
]
REPO = pathlib.Path(__file__).resolve().parent.parent
OUT_MD = REPO / "sc/ugen-catalog.md"
OUT_JSON = REPO / "sc/ugen-catalog.json"

FIELD = re.compile(r"^(TITLE|summary|categories|related|RELATED)::\s*(.*)$", re.I)
ARG = re.compile(r"^argument::\s*(\S+)\s*$")
DEFAULT = re.compile(r"default(?:s)?\s*(?:is|are|:)\s*(.+)$", re.I)


def parse(path: pathlib.Path) -> dict | None:
    try:
        text = path.read_text(errors="replace")
    except OSError:
        return None
    name = path.stem
    title = summary = cats = ""
    args: list[dict] = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        m = FIELD.match(line)
        if m:
            key, val = m.group(1).lower(), m.group(2).strip()
            if key == "title":
                title = val
            elif key == "summary":
                summary = val
            elif key == "categories":
                cats = val
        else:
            a = ARG.match(line)
            if a:
                argname = a.group(1)
                # gather the description: following non-empty indented lines
                desc, default = [], ""
                j = i + 1
                while j < len(lines) and len(desc) < 3:
                    nxt = lines[j].strip()
                    if not nxt or FIELD.match(lines[j].rstrip()) or ARG.match(lines[j].rstrip()) \
                       or nxt.endswith("::"):
                        break
                    desc.append(nxt)
                    dm = DEFAULT.search(nxt)
                    if dm and not default:
                        default = dm.group(1).strip().rstrip(".")
                    j += 1
                args.append({"name": argname,
                             "desc": " ".join(desc)[:200],
                             "default": default})
        i += 1
    if not cats and not summary:
        return None
    return {"name": name, "title": title or name, "summary": summary,
            "categories": [c.strip() for c in cats.split(">") if c.strip()],
            "args": args, "source": str(path)}


def collect() -> list[dict]:
    seen: dict[str, dict] = {}
    for base in HELP_DIRS:
        if not base.exists():
            continue
        for p in base.rglob("Classes/*.schelp"):
            entry = parse(p)
            if entry and entry["name"] not in seen:
                seen[entry["name"]] = entry
    return sorted(seen.values(), key=lambda e: e["name"].lower())


def is_ugen(e: dict) -> bool:
    cats = " ".join(e["categories"]).lower()
    return "ugen" in cats


def write_markdown(entries: list[dict]) -> None:
    ugens = [e for e in entries if is_ugen(e)]
    by_cat: dict[str, list[dict]] = {}
    for e in ugens:
        cat = e["categories"][0] if e["categories"] else "uncategorised"
        by_cat.setdefault(cat, []).append(e)
    lines = ["# UGen catalogue (generated by tools/ugen_catalog.py)",
             "",
             f"{len(ugens)} UGens with documentation on this machine, grouped by "
             f"category. Search it with `tools/ugen_catalog.py --find <regex>`.",
             ""]
    for cat in sorted(by_cat):
        lines.append(f"## {cat}")
        lines.append("")
        for e in sorted(by_cat[cat], key=lambda x: x["name"].lower()):
            args = ", ".join(a["name"] for a in e["args"][:12])
            extra = "…" if len(e["args"]) > 12 else ""
            lines.append(f"- **{e['name']}** — {e['summary'] or e['title']}")
            if args:
                lines.append(f"  - args: `{args}{extra}`")
        lines.append("")
    OUT_MD.write_text("\n".join(lines))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--find", help="regex to search names, summaries, args, categories")
    ap.add_argument("--args", action="store_true", help="show argument lists in results")
    ap.add_argument("--ugens-only", action="store_true", default=True)
    a = ap.parse_args()

    entries = collect()
    if not entries:
        print("no help files found", file=sys.stderr)
        return 1

    if a.find:
        rx = re.compile(a.find, re.I)
        hits = []
        for e in entries:
            blob = " ".join([e["name"], e["title"], e["summary"],
                             " ".join(e["categories"]),
                             " ".join(x["name"] for x in e["args"])])
            if rx.search(blob):
                hits.append(e)
        print(f"{len(hits)} match(es) for /{a.find}/i\n")
        for e in hits[:40]:
            print(f"{e['name']:26s} {e['summary'] or e['title']}")
            print(f"{'':26s} categories: {', '.join(e['categories'])}")
            if a.args and e["args"]:
                for arg in e["args"]:
                    d = f"  (default {arg['default']})" if arg["default"] else ""
                    print(f"{'':26s}   {arg['name']}{d}: {arg['desc'][:110]}")
        return 0

    write_markdown(entries)
    OUT_JSON.write_text(json.dumps(entries, indent=1))
    ugens = [e for e in entries if is_ugen(e)]
    print(f"{len(entries)} documented classes, {len(ugens)} UGens")
    print(f"-> {OUT_MD.relative_to(REPO)}")
    print(f"-> {OUT_JSON.relative_to(REPO)}")
    with_args = sum(1 for e in ugens if e["args"])
    print(f"{with_args} UGens include argument lists")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
